apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
  ports:
  - protocol: TCP
    port: 8000       # External port to access the service
    targetPort: 80   # Must match the container port (FastAPI typically uses 80)
  type: LoadBalancer  # Creates an external load balancer (in cloud environments)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  selector:
    matchLabels:
      app: fastapi-app
  replicas: 4        # Number of pods to run
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-container
        image: kamalcis/fastapi-app:latest  # Your Docker Hub image
        imagePullPolicy: Always            # Changed from Never to pull from registry
        ports:
        - containerPort: 80                # Must match your FastAPI app's port
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"